{{- if .Values.secretenv.enabled }}
{{- $fullName := include "nessus.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
type: Opaque
data:
  ACTIVATION_CODE: {{ .Values.secretenv.activationcode }}
  PASSWORD: {{ .Values.secretenv.password }}
{{- end }}